/**
 * UI Translations for MedGuard AI
 * English (en) and Urdu (ur)
 *
 * Usage: import translations and access via t('key')
 */

export const translations = {
  en: {
    // Navigation
    nav: {
      home: 'Home',
      scan: 'Scan',
      search: 'Search',
      about: 'About',
    },

    // Home page
    home: {
      trustedTool: 'Trusted Screening Tool',
      scanTitle: 'Scan Medicine Packaging',
      scanDesc: 'Upload a photo of medicine packaging for a risk assessment',
      startScan: 'Start Scan',
      searchTitle: 'Search Medicine Name',
      searchDesc: 'Look up general information about common medicines',
      searchNow: 'Search Now',
      howItWorks: 'How It Works',
      step1Title: '1. Upload or Search',
      step1Desc: 'Take a photo of medicine packaging or search for a medicine by name',
      step2Title: '2. AI Analysis',
      step2Desc: 'Our AI examines packaging indicators and cross-references medicine data',
      step3Title: '3. Get Guidance',
      step3Desc: 'Receive a risk assessment with clear next steps and verification guidance',
      screeningOnly: 'Screening Tool Only',
      privateSecure: 'Private & Secure',
      notDiagnosis: 'Not a Diagnosis',
    },

    // Scan page
    scan: {
      title: 'Scan Medicine Packaging',
      subtitle: 'Upload a clear photo of medicine packaging for an AI risk assessment',
      tipsTitle: 'Tips for best results:',
      tip1: 'Take a clear photo of the full package in good lighting',
      tip2: 'Make sure text, brand name, and barcode are visible',
      tip3: 'Include the expiry date and batch number area if possible',
      tip4: 'Avoid blurry or dark images',
      analyseButton: 'Analyse Packaging',
      disclaimer: 'This tool provides screening-level risk assessment only. It cannot confirm whether a medicine is genuine or counterfeit.',
    },

    // Search page
    search: {
      title: 'Search Medicine Information',
      subtitle: 'Look up general information about common medicines available in Pakistan',
      placeholder: 'Type a medicine name (e.g. Panadol, Brufen)...',
      recentSearches: 'Recent Searches',
      popularMedicines: 'Popular Medicines',
      noLocalMatch: 'No local match for',
      searchWithAI: 'Search with AI',
    },

    // Analysis page
    analysis: {
      title: 'Analysing Your Image',
      statusMessage: 'Please wait while our AI examines the packaging...',
      failed: 'Analysis Failed',
      errorDefault: 'Something went wrong. Please try again.',
      tryAgain: 'Try Again',
      uploadNew: 'Upload New Image',
      loadingResults: 'Loading results...',
      preparing: 'Preparing analysis...',
    },

    // Result page
    result: {
      title: 'Risk Assessment Result',
      extractedInfo: 'Extracted Information',
      medicineName: 'Medicine Name',
      activeIngredient: 'Active Ingredient',
      strength: 'Strength',
      manufacturer: 'Manufacturer',
      batchNumber: 'Batch / Lot Number',
      manufacturingDate: 'Manufacturing Date',
      expiryDate: 'Expiry Date',
      registrationInfo: 'Registration Info',
      barcodeVisible: 'Barcode Visible',
      qrCodeVisible: 'QR Code Visible',
      yes: 'Yes',
      no: 'No',
      observations: 'Observations',
      concerns: 'Concerns',
      missingInfo: 'Information Not Visible',
      recommendations: 'Recommended Actions',
      scanAnother: 'Scan Another',
      goHome: 'Go Home',
    },

    // Medicine info page
    medicineInfo: {
      notFound: 'Medicine Not Found',
      notFoundMessage: 'We couldn\'t find information for',
      inDatabase: 'in our database.',
      backToSearch: 'Back to Search',
      aiGeneratedTitle: 'AI-generated general information',
      aiGeneratedDesc: 'This information was generated by AI and may not be complete or accurate. Verify with a pharmacist or official medicine leaflet before use.',
      notIdentifiedTitle: 'Medicine could not be confidently identified',
      notIdentifiedDesc: 'The information below may refer to a different medicine. Please check the spelling or provide the active ingredient name.',
      activeIngredient: 'Active Ingredient:',
      generalUses: 'General Uses',
      dosageTitle: 'General Dosage Information',
      precautions: 'Precautions',
      sideEffects: 'Common Side Effects',
      interactions: 'Interactions',
      storage: 'Storage',
      sources: 'Reliable Sources',
    },

    // About page
    about: {
      title: 'About',
      subtitle: 'AI-powered medicine safety screening for Pakistan',
      whatIs: 'What MedGuard AI Is',
      whatIsNot: 'What MedGuard AI Is NOT',
      safetyGuidelines: 'Safety Guidelines for Users',
      projectInfo: 'Project Info',
      team: 'Team',
      contact: 'Contact & Feedback',
      isItem1: 'A screening tool that helps identify potential warning signs in medicine packaging',
      isItem2: 'A source of general, publicly available medicine information (uses, dosage, side effects)',
      isItem3: 'A tool to guide users toward proper verification by qualified professionals',
      isItem4: 'Designed for the public health context of Pakistan',
      notItem1: 'Not a diagnostic tool',
      notItem1Desc: 'it cannot diagnose any medical condition',
      notItem2: 'Not a counterfeit detector',
      notItem2Desc: 'it cannot confirm whether a medicine is genuine or fake',
      notItem3: 'Not a substitute for professional advice',
      notItem3Desc: 'always consult a doctor or pharmacist',
      notItem4: 'Not a treatment recommendation engine',
      notItem4Desc: 'it does not recommend specific treatments',
      safetyItem1: 'Always purchase medicines from licensed, registered pharmacies',
      safetyItem2: 'If you suspect a medicine may be substandard, do not use it -- consult a pharmacist',
      safetyItem3: 'Report suspicious medicines to the Drug Regulatory Authority of Pakistan (DRAP)',
      safetyItem4: 'Never self-medicate for serious conditions -- always see a qualified doctor',
      safetyItem5: 'Keep all medicines out of reach of children',
      safetyItem6: 'Check expiry dates before using any medicine',
      projectDesc1: 'was built for the',
      projectDesc2: 'The project aims to leverage AI technology to help address the public health challenge of substandard and counterfeit medicines in Pakistan.',
      projectDesc3: 'This prototype demonstrates the concept. Future versions plan to integrate Alibaba Cloud AI services for real image analysis and medicine verification.',
      teamPlaceholder: 'Team members will be listed here',
      contactDesc: 'We welcome feedback and suggestions. Contact details will be added here.',
    },

    // Disclaimers
    disclaimer: {
      screening: 'This is a screening assessment only. This tool cannot confirm whether a medicine is genuine or counterfeit. Always consult a qualified healthcare professional or pharmacist.',
      general: 'MedGuard AI is a screening tool and does not provide medical diagnosis or treatment advice. Always consult a qualified healthcare professional for health decisions.',
      medicineInfo: 'This is general information only and is not a substitute for professional medical advice. Consult a healthcare professional for personalized diagnosis or treatment.',
    },

    // Common
    common: {
      na: 'N/A',
    },

    // Risk labels
    risk: {
      LOW_CONCERN: 'Low Concern',
      NEEDS_VERIFICATION: 'Needs Verification',
      HIGH_CONCERN: 'High Concern',
    },
  },

  ur: {
    // Navigation
    nav: {
      home: 'ہوم',
      scan: 'اسکین',
      search: 'تلاش',
      about: 'تعارف',
    },

    // Home page
    home: {
      trustedTool: 'قابل اعتماد اسکریننگ ٹول',
      scanTitle: 'ادویات کی پیکنگ اسکین کریں',
      scanDesc: 'رسک اسسمنٹ کے لیے ادویات کی پیکنگ کی تصویر اپ لوڈ کریں',
      startScan: 'اسکین شروع کریں',
      searchTitle: 'دوا کا نام تلاش کریں',
      searchDesc: 'عام ادویات کے بارے میں عمومی معلومات دیکھیں',
      searchNow: 'ابھی تلاش کریں',
      howItWorks: 'یہ کیسے کام کرتا ہے',
      step1Title: '1. اپ لوڈ یا تلاش کریں',
      step1Desc: 'ادویات کی پیکنگ کی تصویر لیں یا نام سے دوا تلاش کریں',
      step2Title: '2. AI تجزیہ',
      step2Desc: 'ہمارا AI پیکنگ کے اشاروں کا جائزہ لیتا ہے اور دوا کے ڈیٹا سے موازنہ کرتا ہے',
      step3Title: '3. رہنمائی حاصل کریں',
      step3Desc: 'واضح اگلے اقدامات اور تصدیقی رہنمائی کے ساتھ رسک اسسمنٹ حاصل کریں',
      screeningOnly: 'صرف اسکریننگ ٹول',
      privateSecure: 'نجی اور محفوظ',
      notDiagnosis: 'تشخیص نہیں',
    },

    // Scan page
    scan: {
      title: 'ادویات کی پیکنگ اسکین کریں',
      subtitle: 'AI رسک اسسمنٹ کے لیے ادویات کی پیکنگ کی صاف تصویر اپ لوڈ کریں',
      tipsTitle: 'بہترین نتائج کے لیے تجاویز:',
      tip1: 'اچھی روشنی میں مکمل پیکیج کی صاف تصویر لیں',
      tip2: 'یقینی بنائیں کہ متن، برانڈ نام اور بار کوڈ نظر آ رہے ہیں',
      tip3: 'اگر ممکن ہو تو expiry date اور batch number کا علاقہ شامل کریں',
      tip4: 'دھندلی یا تاریک تصاویر سے گریز کریں',
      analyseButton: 'پیکنگ کا تجزیہ کریں',
      disclaimer: 'یہ ٹول صرف اسکریننگ سطح کی رسک اسسمنٹ فراہم کرتا ہے۔ یہ تصدیق نہیں کر سکتا کہ دوا اصلی ہے یا نقلی۔',
    },

    // Search page
    search: {
      title: 'دوا کی معلومات تلاش کریں',
      subtitle: 'پاکستان میں دستیاب عام ادویات کے بارے میں عمومی معلومات دیکھیں',
      placeholder: 'دوا کا نام لکھیں (مثلاً Panadol، Brufen)...',
      recentSearches: 'حالیہ تلاش',
      popularMedicines: 'مقبول ادویات',
      noLocalMatch: 'کوئی مقامی نتیجہ نہیں ملا',
      searchWithAI: 'AI سے تلاش کریں',
    },

    // Analysis page
    analysis: {
      title: 'آپ کی تصویر کا تجزیہ ہو رہا ہے',
      statusMessage: 'براہ کرم انتظار کریں جب ہمارا AI پیکنگ کا جائزہ لے رہا ہے...',
      failed: 'تجزیہ ناکام',
      errorDefault: 'کچھ غلط ہو گیا۔ براہ کرم دوبارہ کوشش کریں۔',
      tryAgain: 'دوبارہ کوشش کریں',
      uploadNew: 'نئی تصویر اپ لوڈ کریں',
      loadingResults: 'نتائج لوڈ ہو رہے ہیں...',
      preparing: 'تجزیہ تیار ہو رہا ہے...',
    },

    // Result page
    result: {
      title: 'رسک اسسمنٹ کا نتیجہ',
      extractedInfo: 'نکالی گئی معلومات',
      medicineName: 'دوا کا نام',
      activeIngredient: 'فعال جزو',
      strength: 'طاقت',
      manufacturer: 'مینوفیکچرر',
      batchNumber: 'بیچ / لاٹ نمبر',
      manufacturingDate: 'مینوفیکچرنگ کی تاریخ',
      expiryDate: 'ایکسپائری کی تاریخ',
      registrationInfo: 'رجسٹریشن کی معلومات',
      barcodeVisible: 'بار کوڈ نظر آیا',
      qrCodeVisible: 'QR کوڈ نظر آیا',
      yes: 'ہاں',
      no: 'نہیں',
      observations: 'مشاہدات',
      concerns: 'خدشات',
      missingInfo: 'معلومات نظر نہیں آئیں',
      recommendations: 'تجویز کردہ اقدامات',
      scanAnother: 'دوسری اسکین کریں',
      goHome: 'ہوم پر جائیں',
    },

    // Medicine info page
    medicineInfo: {
      notFound: 'دوا نہیں ملی',
      notFoundMessage: 'ہمیں معلومات نہیں مل سکیں',
      inDatabase: 'ہمارے ڈیٹا بیس میں۔',
      backToSearch: 'تلاش پر واپس جائیں',
      aiGeneratedTitle: 'AI سے تیار کردہ عمومی معلومات',
      aiGeneratedDesc: 'یہ معلومات AI نے تیار کی ہیں اور مکمل یا درست نہیں ہو سکتیں۔ استعمال سے پہلے فارماسسٹ یا سرکاری دوا کے پمفلٹ سے تصدیق کریں۔',
      notIdentifiedTitle: 'دوا کی باقاعدہ شناخت نہیں ہو سکی',
      notIdentifiedDesc: 'نیچے دی گئی معلومات کسی اور دوا سے متعلق ہو سکتی ہیں۔ براہ کرم ہجے چیک کریں یا فعال جزو کا نام فراہم کریں۔',
      activeIngredient: 'فعال جزو:',
      generalUses: 'عام استعمال',
      dosageTitle: 'عمومی خوراک کی معلومات',
      precautions: 'احتیاطی تدابیر',
      sideEffects: 'عام ضمنی اثرات',
      interactions: 'تعاملات',
      storage: 'ذخیرہ',
      sources: 'قابل اعتماد ذرائع',
    },

    // About page
    about: {
      title: 'تعارف',
      subtitle: 'پاکستان کے لیے AI سے چلنے والی دوا کی حفاظتی اسکریننگ',
      whatIs: 'MedGuard AI کیا ہے',
      whatIsNot: 'MedGuard AI کیا نہیں ہے',
      safetyGuidelines: 'صارفین کے لیے حفاظتی رہنما خطوط',
      projectInfo: 'پروجیکٹ کی معلومات',
      team: 'ٹیم',
      contact: 'رابطہ اور فیڈبیک',
      isItem1: 'ایک اسکریننگ ٹول جو ادویات کی پیکنگ میں ممکنہ انتباہی علامات کی نشاندہی کرنے میں مدد کرتا ہے',
      isItem2: 'عام، عوامی طور پر دستیاب دوا کی معلومات کا ذریعہ (استعمال، خوراک، ضمنی اثرات)',
      isItem3: 'ایک ٹول جو صارفین کو اہل پیشہ ور افراد سے مناسب تصدیق کی طرف رہنمائی کرتا ہے',
      isItem4: 'پاکستان کے عوامی صحت کے تناظر کے لیے ڈیزائن کیا گیا',
      notItem1: 'تشخیصی ٹول نہیں',
      notItem1Desc: 'یہ کسی بھی طبی حالت کی تشخیص نہیں کر سکتا',
      notItem2: 'نقلی کا پتہ لگانے والا نہیں',
      notItem2Desc: 'یہ تصدیق نہیں کر سکتا کہ دوا اصلی ہے یا نقلی',
      notItem3: 'پیشہ ورانہ مشورے کا متبادل نہیں',
      notItem3Desc: 'ہمیشہ ڈاکٹر یا فارماسسٹ سے مشورہ کریں',
      notItem4: 'علاج کی سفارش کا انجن نہیں',
      notItem4Desc: 'یہ مخصوص علاج کی سفارش نہیں کرتا',
      safetyItem1: 'ہمیشہ لائسنس یافتہ، رجسٹرڈ فارمیسیوں سے ادویات خریدیں',
      safetyItem2: 'اگر آپ کو شبہ ہے کہ دوا ناقص ہو سکتی ہے، تو استعمال نہ کریں -- فارماسسٹ سے مشورہ کریں',
      safetyItem3: 'مشکوک ادویات کی اطلاع ڈرگ ریگولیٹری اتھارٹی آف پاکستان (DRAP) کو دیں',
      safetyItem4: 'سنگین حالات میں کبھی خود علاج نہ کریں -- ہمیشہ اہل ڈاکٹر سے ملیں',
      safetyItem5: 'تمام ادویات بچوں کی پہنچ سے دور رکھیں',
      safetyItem6: 'کسی بھی دوا کو استعمال کرنے سے پہلے ایکسپائری کی تاریخ چیک کریں',
      projectDesc1: 'کے لیے بنایا گیا تھا',
      projectDesc2: 'اس پروجیکٹ کا مقصد AI ٹیکنالوجی سے فائدہ اٹھاتے ہوئے پاکستان میں ناقص اور نقلی ادویات کے عوامی صحت کے چیلنج سے نمٹنے میں مدد کرنا ہے۔',
      projectDesc3: 'یہ پروٹوٹائپ تصور کو ظاہر کرتا ہے۔ مستقبل کے ورژن میں حقیقی تصویری تجزیہ اور دوا کی تصدیق کے لیے Alibaba Cloud AI خدمات کو شامل کرنے کا منصوبہ ہے۔',
      teamPlaceholder: 'ٹیم ممبران یہاں درج ہوں گے',
      contactDesc: 'ہم فیڈبیک اور تجاویز کا خیرمقدم کرتے ہیں۔ رابطے کی تفصیلات یہاں شامل کی جائیں گی۔',
    },

    // Disclaimers
    disclaimer: {
      screening: 'یہ صرف اسکریننگ اسسمنٹ ہے۔ یہ ٹول تصدیق نہیں کر سکتا کہ دوا اصلی ہے یا نقلی۔ ہمیشہ اہل ہیلتھ کیئر پیشہ ور یا فارماسسٹ سے مشورہ کریں۔',
      general: 'MedGuard AI ایک اسکریننگ ٹول ہے اور طبی تشخیص یا علاج کا مشورہ نہیں دیتا۔ صحت کے فیصلوں کے لیے ہمیشہ اہل ہیلتھ کیئر پیشہ ور سے مشورہ کریں۔',
      medicineInfo: 'یہ صرف عمومی معلومات ہیں اور پیشہ ورانہ طبی مشورے کا متبادل نہیں ہیں۔ ذاتی تشخیص یا علاج کے لیے ہیلتھ کیئر پیشہ ور سے مشورہ کریں۔',
    },

    // Common
    common: {
      na: 'N/A',
    },

    // Risk labels
    risk: {
      LOW_CONCERN: 'کم تشویش',
      NEEDS_VERIFICATION: 'تصدیق درکار ہے',
      HIGH_CONCERN: 'زیادہ تشویش',
    },
  },
}

// Helper function to get translation
export function getTranslation(lang, key) {
  const keys = key.split('.')
  let result = translations[lang]
  for (const k of keys) {
    if (result && typeof result === 'object' && k in result) {
      result = result[k]
    } else {
      // Fallback to English
      result = translations.en
      for (const fk of keys) {
        if (result && typeof result === 'object' && fk in result) {
          result = result[fk]
        } else {
          return key // Return key if not found
        }
      }
      return result
    }
  }
  return result
}
